server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/zipcode-address-finder
    username: postgres
    password: 1012
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS"

logging:
  level:
    br.com.brunogodoif: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

application:
    dateformatter: "yyyy-MM-dd HH:mm:ss"