server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/zipcode-address-finder
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: false
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        flush:
          mode: COMMIT
        batch_versioned_data: true
  output:
    ansi:
      enabled: Always
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS"

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    baseline-version: 0

logging:
  level:
    br.com.brunogodoif: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

application:
    dateformatter: "yyyy-MM-dd HH:mm:ss"

